let express = require("express");
let router = express.Router();
const helper = require('../utilities/helper');
const saveCustomerCtrl = require('../controllers/customer/save');
const listCustomerCtrl = require('../controllers/customer/list');
const getoneCustomerCtrl = require('../controllers/customer/getone');
router.post('/', helper.authenticateToken, listCustomerCtrl.list);
router.post('/save', helper.authenticateToken, saveCustomerCtrl.save);
router.post('/getone', helper.authenticateToken, getoneCustomerCtrl.getone);
module.exports = router;
