let express = require("express");
let router = express.Router();
const helper = require('../utilities/helper');
const saveThemeCtrl = require('../controllers/theme/save');
const listThemeCtrl = require('../controllers/theme/list');
const getoneThemeCtrl = require('../controllers/theme/getone');
router.post('/', helper.authenticateToken, listThemeCtrl.list);
router.post('/save', helper.authenticateToken, saveThemeCtrl.save);
router.post('/getone', helper.authenticateToken, getoneThemeCtrl.getone);
module.exports = router;